name: git binaries build
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
  
    steps:
    - uses: actions/checkout@master
    - name: Install build environment
      run: |
        sudo apt-get update
        sudo apt-get install --yes apt-utils
        sudo DEBIAN_FRONTEND=noninteractive apt-get install --yes wget locales appstream cmake pkg-config make libssl-dev libghc-zlib-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip build-essential autoconf
  
    - name: Executing binaries build
      run: bash ./make_binaries.sh
  
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        tag: ${{ github.ref_name }}
        name: "Release build (${{ github.ref_name }})"
        artifacts: "git-*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}